# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
    plugins:
        - custom_lint
    errors:
        invalid_annotation_target: ignore
    exclude:
        - '**.g.dart'

linter:
    rules:
        invalid_annotation_target: ignore
        prefer_single_quotes: true
        prefer_const_constructors: true
        avoid_empty_else: true
        avoid_print: true
        avoid_redundant_argument_values: true
        prefer_final_fields: true
        prefer_final_locals: true
        prefer_final_in_for_each: true
        prefer_const_constructors_in_immutables: true
        prefer_const_declarations: true
        prefer_relative_imports: true
        prefer_void_to_null: true
        prefer_is_empty: true
        prefer_is_not_empty: true
        unnecessary_statements: true
        invariant_booleans: true
        use_colored_boxes: true
        use_decorated_box: true
        use_if_null_to_convert_nulls_to_bools: true
        use_string_in_part_of_directives: true

        #formatting
        lines_longer_than_80_chars: false
        curly_braces_in_flow_control_structures: false

        #pub
        secure_pubspec_urls: true
