name: dir_music_client
description: Starter for Flutter projects.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
    sdk: '>=3.0.1 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    # Localizations
    easy_localization: ^3.0.2
    intl: ^0.18.0
    # Routing
    go_router: ^7.0.2
    # State Management
    flutter_riverpod: ^2.3.6
    # Annotators
    json_annotation: ^4.8.1
    freezed_annotation: ^2.2.0
    # Networking
    dio: ^5.1.2
    dio_http2_adapter: ^2.0.0
    # Misc.
    logger: ^1.1.0
    path_provider: ^2.0.11
    cupertino_icons: ^1.0.2
    equatable: ^2.0.5
    shared_preferences: ^2.1.1
    json_theme: ^4.0.0
    just_audio: ^0.9.34
    audio_session: ^0.1.15
    rxdart: ^0.27.7
    # Hive Store
    # hive_flutter: ^1.1.0

dev_dependencies:
    freezed: ^2.3.4
    json_serializable: ^6.7.0
    build_runner: ^2.4.4
    flutter_test:
        sdk: flutter
    custom_lint: ^0.4.0
    riverpod_lint: ^1.3.2
    flutter_lints: ^2.0.0
    # Hive Generator
    # hive_generator: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/icons/
        - assets/translations/
        - assets/other/

    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
